name: Create Package

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Jump King content
        uses: Skippeh/steamfetch-action@v1
        with:
          username: "${{ secrets.STEAM_USER }}"
          password: "${{ secrets.STEAM_PASS }}"
          dir: "${{ github.workspace }}/game-files"
          os: windows
          app: 1061090
          osarch: 32

          # Download all dll/exe files in root directory
          files: |
            regex:^[^\/\s]+\.(exe|dll)$
      - name: Download AssemblyReflector
        uses: suisei-cn/actions-download-file@v1
        with:
          url: https://github.com/Jump-King-Multiplayer/AssemblyReflector/releases/download/latest/Build.zip
          target: "AssemblyReflector"
      - name: Unzip AssemblyReflector
        shell: bash
        run: unzip AssemblyReflector/Build.zip -d ./AssemblyReflector
      - name: Run AssemblyReflector
        shell: bash
        run: ./AssemblyReflector/AssemblyReflector.exe -i ./game-files/JumpKing.exe -o ./pkg/ref/
      - name: Create package file
        uses: papeloto/action-zip@v1
        with:
          files: ./pkg
          recursive: true
          dest: JKMP.GameDependencies.nupkg
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: JKMP.GameDependencies.nupkg
          path: JKMP.GameDependencies.nupkg
          retention-days: 1